---
name: bosh-lite

releases:
- name: bosh
  version: BOSH_RELEASE_VERSION
  url: file:///tmp/bosh-release.tgz
- name: bosh-warden-cpi
  version: WARDEN_RELEASE_VERSION
  url: file:///tmp/bosh-warden-cpi-release.tgz
- name: garden-linux
  version: GARDEN_LINUX_RELEASE_VERSION
  url: file:///tmp/garden-linux-release.tgz

networks:
- {name: default, type: dynamic}

update:
  canary_watch_time: 5000 - 600000
  update_watch_time: 5000 - 600000

compilation:
  network: default

jobs:
- name: bosh
  instances: 1

  networks:
  - name: default

  templates:
  - {name: nats, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: postgres, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: warden_cpi, release: bosh-warden-cpi}
  - {name: garden, release: garden-linux}

properties:
  ntp: ["0.us.pool.ntp.org"]

  compiled_package_cache:
    provider: local
    options: {blobstore_path: /vagrant/tmp/compiled_package_cache}

  nats:
    user: nats
    password: nats-password
    address: 127.0.0.1
    port: 4222

  blobstore:
    address: 127.0.0.1
    port: 25251
    backend_port: 25552
    agent: {user: agent, password: agent-password}
    director: {user: director, password: director-password}

  postgres: &db
    user: bosh
    password: bosh-password
    host: 127.0.0.1
    port: 5432
    database: bosh

  director:
    name: "Bosh Lite Director"
    address: 127.0.0.1
    max_tasks: 100
    cpi_job: warden_cpi
    db: *db
    flush_arp: true
    enable_post_deploy: true
    enable_dedicated_status_worker: true
    workers: 4
    events:
      record_events: true

    # Compatibility with current garden networking manifest config
    ignore_missing_gateway: true

    # See ca/ directory
    ssl:
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEA6mav2DOdfrostegKBQu/3coZq0A8lEdwtWxN+1xqkeYDvGTQ
        gTLZxULBgW9OalpYB2fKwpBrHVmoINTu/fK6/rPvexc0Z7BdwXTaYBxtrxsNmU7x
        sLaJ/fNiYZSrxvt8tTCn3br99NHfoCJluo8nxI3FYiFsEUUYejQ5X8D6WES02/Fm
        UFfyF+2NMZCpxD6u3S7rg7a7FocsdZoWAgkjeXtimy+kzEpSAsGfB7VgbrDbgjmk
        vqWbsyn1D8bqtrvDKfqpt2A/4Q1xqQMc2WhOw6i3GEKgCA/vQ3tdA60gjfkQ7Ivg
        RSRmpege1CjoJ8KGH8+p6mVWuwvEAIrX58yj+wIDAQABAoIBABVvSHtD1Q4mpjoI
        OwpVFbmJZqmDWUbR9ZuRiNwIinJHD2Zl7a8y4DkqrplQfWI6WrxqoF8EZ9cqQLan
        4ib00GbEO40NBSzKMvii3+lUEC+oEKlJT86yEpJXdFKqDr9GdhP3nBIprFl767Aw
        FQ9nUeKmeDtOBRzbLa7XIbwA4KO7j9rW+R5tDbtg1yJPWSngmx8iFkiImZFIt+X3
        bac8cYEd4gzxCYKOMEfoCwzfYCnbFs+YVi4lQgux3JTLawb3MII5l4vYhqiSGkON
        m8qakvKjbJ8qIchgHXQR+EbrCHwbdaxZ0M/eY1KR8YUbmFYVoXv7IWA3bXxanWJo
        Jv9Iu5kCgYEA/5LDt9eA2CjxVFEWv8NO7ixPygWJep+9s8IteIDYbwgGLGAFk/G2
        DMmPR/sjmSgH+k2AC3a/nrkpbUvQuqxDNb6bJO99YNWSOBlQq+02+kSuwgTCKMRB
        y+zfrULGuDD0D5go6SdbGp4fuyLhL0R0dTFT/C0yb55nIJ7e3rYxIS8CgYEA6srf
        gxkFDrkuQ5efvZyQBmpWdoPSAUqQLk1cUFSMIRcNnf86tLtS1fFgWPmVys/E1J46
        e+n9IeK5vL+lt6Y/rS7L/FNaPgrO3u59ixlJJG5NEpFwyopVpGCAE6wVdsuoXMsz
        +F5deO1fY28bfd4NXnqGNuMN1mtHp9K4LE6JvvUCgYEAjyFDqQ7w4p4zYXQ0WFrq
        NmrsmIh3UQxrMmP6ETWfgLcuteVk2lEREqJDMx3L9vc7WIvUvRbZA+xQ7hv6nsDg
        txWzT4EsZ3HUfMR4sICePJUAhjoh/rDC5JEZR7BRGFCaLq2Zo9HdrM+Hl8dV86HT
        0to4Xc92IprEyLkQuguxAhMCgYEAtBCUbAFDLLB+N55QBuXMWu8wkkG0TAM4Ihp4
        Qq8krLf2XIaCKltDQwqT3ojDBUBkbr9OkPu5g0RTN9sup3KbgSDTlhcCrXQyhSwY
        IhZpTsQ83ZGnE94VojPT5cJiz7GO1GOO3trYCsbZEfQC/HvQevWyeuOVGC08Tgu/
        7VLqNwUCgYEA2j5/4j+cJaFJ+ntjLvPToligaHLkB/9euCS/pnVm+P4gJx50tYV0
        jLBIC5h+qE1w992o3eQaIC/jtanXT/OZzDE8tzojHChsxZjOXEJdjUCE9aaOMKto
        zF3CP73rsEaC2Ml3iyqceLDCFuNsANlS5GwRtkU6Qk02+XDmjklCMh8=
        -----END RSA PRIVATE KEY-----

      # subject=/C=US/O=BOSH/CN=192.168.50.4
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIDHDCCAgSgAwIBAgIJAPJwlYY2wUIzMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
        BAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
        aWRnaXRzIFB0eSBMdGQwIBcNMTYwODI2MjIzMzE5WhgPMjI5MDA2MTAyMjMzMTla
        MDMxCzAJBgNVBAYTAlVTMQ0wCwYDVQQKEwRCT1NIMRUwEwYDVQQDEwwxOTIuMTY4
        LjUwLjQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDqZq/YM51+uiy1
        6AoFC7/dyhmrQDyUR3C1bE37XGqR5gO8ZNCBMtnFQsGBb05qWlgHZ8rCkGsdWagg
        1O798rr+s+97FzRnsF3BdNpgHG2vGw2ZTvGwton982JhlKvG+3y1MKfduv300d+g
        ImW6jyfEjcViIWwRRRh6NDlfwPpYRLTb8WZQV/IX7Y0xkKnEPq7dLuuDtrsWhyx1
        mhYCCSN5e2KbL6TMSlICwZ8HtWBusNuCOaS+pZuzKfUPxuq2u8Mp+qm3YD/hDXGp
        AxzZaE7DqLcYQqAID+9De10DrSCN+RDsi+BFJGal6B7UKOgnwoYfz6nqZVa7C8QA
        itfnzKP7AgMBAAGjHzAdMBsGA1UdEQQUMBKHBMCoMgSCCiouc3NsaXAuaW8wDQYJ
        KoZIhvcNAQEFBQADggEBADVff56wJtocm/+9qlMhm4BTV29MDSEWHMduUb2VMtld
        XqsetkPA9Jq/ZvOOMc9QJgIbcFlPye9wzDbc5ZHkj+/d7G9CqUX0d8+awE+XDIA9
        1bc35aabG/2DQYkTc3n7MHLodhictIAeg8S/FzGLITecxA1p57b9dve23MUvLn1U
        D/zyTVn6q9ZNB3/eQH79OioKygq/Z97YuZWiOgc7J7535EgRiyhJvbzindUCJD9b
        W38X3NeovdOBm8XvxcEqSkkX7doBVFGZMGoGClHOYTUDROYVgQftijItYxLvEMED
        Eu3kbh5DZssZkp8N1cELvYJkM+ke0IHs9ou25BvP4r4=
        -----END CERTIFICATE-----

  hm:
    director_account: {user: admin, password: admin}
    resurrector_enabled: true

  # cpi job template
  warden_cpi:
    host_ip: 10.254.50.4
    warden:
      connect_network: tcp
      connect_address: 127.0.0.1:7777
    agent:
      mbus: nats://nats:nats-password@10.254.50.4:4222
      blobstore:
        provider: dav
        options:
          endpoint: http://10.254.50.4:25251
          user: agent
          password: agent-password

  # garden job template
  garden:
    listen_network: tcp
    listen_address: 0.0.0.0:7777
    disk_quota_enabled: false
    allow_host_access: true
    destroy_containers_on_start: true # avoids snapshots
    default_container_grace_time: 0
